version: '3.8'

services:

  web:
    build: ./project
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload --log-level info
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis

  worker:
    build: ./project
    command: celery worker --app=worker.celery --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
        # AMQP protocol port
      - '5672:5672'
        # HTTP management UI
      - '15672:15672'

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  dashboard:
    build: ./project
    command:  flower --app=worker.celery --port=5555 --broker=amqp://guest:guest@rabbitmq:5672//
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - rabbitmq
      - worker
      - redis
